#!/bin/sh



VER="$( cat /var/www/mm_reader/version )"


SERVICE_NAME=mmServer
PATH_TO_APP="/var/www/mm_reader/$VER/mm_readerx ++++ /var/www/mm_reader/$VER/"
PID_PATH_NAME=/tmp/mm-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
          
            nohup $PATH_TO_APP >> /var/www/mm_reader/mm_log &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
                       
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."                                 
            kill -9 $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";                      
            kill -9 $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."            
             nohup $PATH_TO_APP >> /var/www/mm_reader/mm_log &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac 

